### ISSUE TITLE
Sending big russian text makes message improperly encoded

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [podshumok/python-smpplib#53] opened 2018-07-10 12:18 UTC
Hello.

I have service which sends SMS messages and will accept parameters via SMPP

I'm using this lines of code to send message:

        parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(text)

        client = smpplib.client.Client(sms_host, sms_port)

        client.set_message_sent_handler(
            lambda pdu: sys.stdout.write('sent {} {}\n'.format(pdu.sequence, pdu.message_id)))
        client.set_message_received_handler(
            lambda pdu: sys.stdout.write('delivered {}\n'.format(pdu.receipted_message_id)))

        client.connect()
        client.bind_transceiver(system_id=system_id, password=password)

        for part in parts:
            pdu = client.send_message(
                source_addr_ton=5,
                source_addr_npi=0,
                # Make sure it is a byte string, not unicode:
                source_addr=source_addr,

                dest_addr_ton=1,
                dest_addr_npi=1,
                # Make sure thease two params are byte strings, not unicode:
                destination_addr=dest_addr,
                short_message=part,

                data_coding=encoding_flag,
                esm_class=msg_type_flag,
                registered_delivery=True,
            )

When I try to send russian or any cyrrillic text, SMS service sends me that kind of text:

    Привеееет привввввееееееееет прип�䀄㠄㼄䀄㠄㈄㈄㈄㈄㈄㈄㈄㔄㔄㔄㔄㔄㔄䈄䈄䈄䈄䈄䰄䰄䰄䰀 䴄䈄㸀 㐄�лгий дооолги и оченнь доооолги  т�㔄㔄㔄㨄䄄䈀 㐄㬄伀 㼄䀄㸄㈄㔄䀄㨄㠀 㼄䀄㸄㈄㔄䀄㨄  䄄㠄䄄䈄�мы система вклбченр вы йцк   нужн�  㨄㬄〄㈄  㤄䘄䌄㨄㔄�

The interesting thing is that some parts are correct and some parts become weird chineese symbols.

Why this is happening?

**Comment by eigenein** [comment] 2018-10-11 14:49
Hi,

Does this still happen for you?

**Comment by eigenein** [comment] 2018-10-11 15:33
@SuperMasterBlasterLaser Could you please show how it differs from the current `make_parts_encoded` implementation and/or provide a unit test for that (input text and expected parts in output)?

Then I'll take a look at it.

**Comment by SuperMasterBlasterLaser** [comment] 2018-10-12 03:58
@eigenein Made pull request with this code.

I have been using this libs code which was downloaded from somewhere else.

**Comment by eigenein** [comment] 2018-10-15 13:06
Reproduced. The thing is: `UCS2_MP_SIZE` is an odd number, so `make_parts_encoded` splits a message in the middle of a character. That's why every other part is broken, because it starts with an incorrect byte.

**Comment by eigenein** [comment] 2018-10-15 13:43
#49 is related

**Comment by eigenein** [comment] 2018-10-15 13:47
Fixed by https://github.com/podshumok/python-smpplib/pull/59

**Closed by eigenein** 2018-10-15 13:47 UTC

**Comment by SuperMasterBlasterLaser** [comment] 2018-10-16 03:46
@eigenein That is great.
